"""Added a column

Revision ID: 386f4f666051
Revises: 8729ae41e41b
Create Date: 2020-12-06 23:35:48.717324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386f4f666051'
down_revision = '8729ae41e41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('date_added', sa.DateTime(timezone=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'date_added')
    # ### end Alembic commands ###
